### ISSUE TITLE
Missing bluebird dependency

### ISSUE THREAD

**Issue by marcelshields** [horike37/serverless-delete-loggroups#1]
When trying to deploy, I'm getting the error:

![bluebird-error](https://cloud.githubusercontent.com/assets/655718/22473436/ef8f6234-e7a6-11e6-8c60-3201a31bf673.png)

I believe bluebird module is missing from package.json.

**Comment by horike37** [comment]
@marcelshields 
Thank you for the report!
Just fixed and released https://github.com/horike37/serverless-delete-loggroups/releases/tag/0.2.0.

Please upgrade it.
The case is my mistake. Sorry..
